#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from os import chdir
from os.path import dirname, realpath
from sys import argv
from base import *

if __name__ == '__main__':
    chdir(dirname(realpath(__file__)))

    if len(argv) > 1:
        a = argv[1]
        if a in ['p', 'privado', 'incognito']:
            abrir_url(argv[1:], '--incognito')
        elif a in ['t', 'tor']:
            abrir_url(argv[1:], '--incognito --tor')
        elif a in ['l', 'listar-urls']:
            listar_urls(argv[1:])
        elif a in ['a', 'agregar-url']:
            agregar_url(argv[1:])
        elif a in ['ec', 'editar-configuracion']:
            editar('configuracion.py')
        elif a in ['eu', 'editar-urls']:
            editar('urls.py')
        elif a in ['h', 'help', 'y', 'ayuda']:
            ayuda()
        elif idu_valido(a):
            abrir_url(argv)
        elif url_valida(a):
            abrir_url(argv)
